// Generated by Melange
'use strict';

var Main = require("./Main.bs.js");
var React = require("react");
var ReactDom = require("react-dom");

var root = document.querySelector("#root");

if (root == null) {
  console.log("Coudn't find #root element to mount the React app.");
} else {
  ReactDom.render(React.createElement(Main.make, {}), root);
}

/* root Not a pure module */
