// Generated by Melange
'use strict';

var React = require("react");

console.log("Hello world");

function Main(Props) {
  return React.createElement("div", undefined, "Hello React");
}

var make = Main;

exports.make = make;
/*  Not a pure module */
